<?php
/**
 * @author       JoomWorker
 * @email        info@joomla.work
 * @url          http://www.joomla.work
 * @copyright    Copyright (c) 2010 - 2019 JoomWorker
 * @license      GNU General Public License version 2 or later
 * @date         2019/01/01 09:30
 */
//no direct accees
defined('_JEXEC') or die ('Restricted access');

// Common
JText::script('COM_JWPAGEFACTORY_FRONTEND_EDITOR');
JText::script('COM_JWPAGEFACTORY_PREVIEW');
JText::script('COM_JWPAGEFACTORY_APPLY');
JText::script('COM_JWPAGEFACTORY_CANCEL');
JText::script('COM_JWPAGEFACTORY_DELETE_COLUMN_CONFIRMATION');

// Media Manager
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_UPLOAD_FILES');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_CLOSE');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_INSERT');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_SEARCH');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_CANCEL');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_DELETE');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_CONFIRM_DELETE');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_LOAD_MORE');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_UNSUPPORTED_FORMAT');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_BROWSE_MEDIA');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_BROWSE_FOLDERS');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_CREATE_FOLDER');
JText::script('COM_JWPAGEFACTORY_ADDON_ICON_SELECT');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_ENTER_DIRECTORY_NAME');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_MEDIA_UPLOADING');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_UPLOAD_FAILED');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_MEDIA_LARGE');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_FILE_NOT_SUPPORTED');

// Row
JText::script('COM_JWPAGEFACTORY_ROW_OPTIONS');
JText::script('COM_JWPAGEFACTORY_ADD_NEW_ROW');
JText::script('COM_JWPAGEFACTORY_DUPLICATE_ROW');
JText::script('COM_JWPAGEFACTORY_DISABLE_ROW');
JText::script('COM_JWPAGEFACTORY_ENABLE_ROW');
JText::script('COM_JWPAGEFACTORY_COPY_ROW');
JText::script('COM_JWPAGEFACTORY_ROW_COPIED');
JText::script('COM_JWPAGEFACTORY_PASTED');
JText::script('COM_JWPAGEFACTORY_PASTE_ROW');
JText::script('COM_JWPAGEFACTORY_DELETE_ROW');
JText::script('COM_JWPAGEFACTORY_ROW_TOGGLE');
JText::script('COM_JWPAGEFACTORY_DELETE_ROW_CONFIRMATION');
JText::script('COM_JWPAGEFACTORY_ROW_COLUMNS_MANAGEMENT');
JText::script('COM_JWPAGEFACTORY_GLOBAL_CUSTOM');
JText::script('COM_JWPAGEFACTORY_ROW_COLUMNS_GENERATE');
JText::script('COM_JWPAGEFACTORY_IMPORT_PAGE');
JText::script('COM_JWPAGEFACTORY_IMPORT_PAGE_ALT');
JText::script('COM_JWPAGEFACTORY_EXPORT_PAGE');
JText::script('COM_JWPAGEFACTORY_PAGE_TEMPLATES');
JText::script('COM_JWPAGEFACTORY_UNDO');
JText::script('COM_JWPAGEFACTORY_REDO');
JText::script('COM_JWPAGEFACTORY_SAVE');
JText::script('COM_JWPAGEFACTORY_SAVE_ROW');

//Addon
JText::script('COM_JWPAGEFACTORY_ROW_COLUMNS_OPTIONS');
JText::script('COM_JWPAGEFACTORY_DELETE_COLUMN');
JText::script('COM_JWPAGEFACTORY_ADD_NEW_ADDON');
JText::script('COM_JWPAGEFACTORY_ADDON');
JText::script('COM_JWPAGEFACTORY_DELETE_ADDON');
JText::script('COM_JWPAGEFACTORY_DUPLICATE_ADDON');
JText::script('COM_JWPAGEFACTORY_EDIT_ADDON');
JText::script('COM_JWPAGEFACTORY_ADDONS_LIST');
JText::script('COM_JWPAGEFACTORY_ALL');
JText::script('COM_JWPAGEFACTORY_MODAL_CLOSE');
JText::script('COM_JWPAGEFACTORY_DISABLE_COLUMN');
JText::script('COM_JWPAGEFACTORY_ENABLE_COLUMN');

JText::script('COM_JWPAGEFACTORY_YES');
JText::script('COM_JWPAGEFACTORY_NO');
JText::script('COM_JWPAGEFACTORY_PAGE_TEMPLATES_LIST');
JText::script('COM_JWPAGEFACTORY_PAGE_TEMPLATE_LOAD');
JText::script('COM_JWPAGEFACTORY_ENABLE_ADDON');
JText::script('COM_JWPAGEFACTORY_DISABLE_ADDON');
JText::script('COM_JWPAGEFACTORY_SAVE_ADDON');
JText::script('COM_JWPAGEFACTORY_ADDON_PARENT_COLUMN');
JText::script('COM_JWPAGEFACTORY_ADD_NEW_INNER_ROW');
JText::script('COM_JWPAGEFACTORY_MOVE_COLUMN');

JText::script('COM_JWPAGEFACTORY_DAY');
JText::script('COM_JWPAGEFACTORY_DAYS');
JText::script('COM_JWPAGEFACTORY_HOUR');
JText::script('COM_JWPAGEFACTORY_HOURS');
JText::script('COM_JWPAGEFACTORY_MINUTE');
JText::script('COM_JWPAGEFACTORY_MINUTES');
JText::script('COM_JWPAGEFACTORY_SECOND');
JText::script('COM_JWPAGEFACTORY_SECONDS');

JText::script('COM_JWPAGEFACTORY_ADDON_OPTIN_FORM_SUBCSCRIBE');
JText::script('COM_JWPAGEFACTORY_ADDON_AJAX_CONTACT_NAME');
JText::script('COM_JWPAGEFACTORY_ADDON_AJAX_CONTACT_EMAIL');

//Added by adan20190111
JText::script('COM_JWPAGEFACTORY_CATEGORIES');
JText::script('COM_JWPAGEFACTORY_LAYOUT_BUNDLES');
JText::script('COM_JWPAGEFACTORY_ADD_SECTION');
JText::script('COM_JWPAGEFACTORY_SECTIONS_LIBRARY');
JText::script('COM_JWPAGEFACTORY_MY_SECTIONS');
JText::script('COM_JWPAGEFACTORY_MY_SECTIONS_NO_SECTION_FOUND');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_DRAG_DROP_UPLOAD');
JText::script('COM_JWPAGEFACTORY_DRAG');
JText::script('COM_JWPAGEFACTORY_TIPS_WAIT');
JText::script('COM_JWPAGEFACTORY_DELETE');
JText::script('COM_JWPAGEFACTORY_ADD_ITEM');
JText::script('COM_JWPAGEFACTORY_ICON_SELECT');
JText::script('COM_JWPAGEFACTORY_ADD_TO_MENU');
JText::script('COM_JWPAGEFACTORY_EMPTY_CONTENT');
JText::script('COM_JWPAGEFACTORY_MY_ADDONS');
JText::script('COM_JWPAGEFACTORY_PAGE_SETTINGS');
JText::script('COM_JWPAGEFACTORY_BACK');
JText::script('COM_JWPAGEFACTORY_SEARCH');
JText::script('COM_JWPAGEFACTORY_PAGES');

//Added by adan20190115
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_ALL_ITEMS');
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_IMAGES');
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_VIDEOS');
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_AUDIOS');
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_ATTACHMENTS');
JText::script('COM_JWPAGEFACTORY_MEDIA_CATEGORIES_BROWSE_FOLDERS');
JText::script('COM_JWPAGEFACTORY_MEDIA_MANAGER_MEDIA_ALL');
JText::script('COM_JWPAGEFACTORY_MEDIA_CHOOSE_YOUR_IMAGE');
JText::script('COM_JWPAGEFACTORY_MEDIA_CHOOSE_YOUR_VIDEO');
JText::script('COM_JWPAGEFACTORY_MEDIA_CHOOSE_YOUR_AUDIO');
JText::script('COM_JWPAGEFACTORY_MEDIA_REMOVE');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_GENERAL');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_STYLE');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_ADVANCED');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_RESPONSIVE');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_ANIMATION');
JText::script('COM_JWPAGEFACTORY_ADDON_TAB_INTERACTION');

//Added by adan20190116
JText::script('COM_JWPAGEFACTORY');
JText::script('COM_JWPAGEFACTORY_ITEM');
JText::script('COM_JWPAGEFACTORY_ADDONS');
JText::script('COM_JWPAGEFACTORY_BLOCKS');
JText::script('COM_JWPAGEFACTORY_LAYOUTS');
JText::script('COM_JWPAGEFACTORY_TOOLS');
JText::script('COM_JWPAGEFACTORY_SELECT_CATEGORY');
JText::script('COM_JWPAGEFACTORY_CLOSE');
JText::script('COM_JWPAGEFACTORY_SAVE_ROW_PLACEHOLDER');
JText::script('COM_JWPAGEFACTORY_SAVE_ADDON_PLACEHOLDER');
JText::script('COM_JWPAGEFACTORY_CREATE_PAGE');
JText::script('COM_JWPAGEFACTORY_CREATE_PAGE_TITLE');
JText::script('COM_JWPAGEFACTORY_CREATE_PAGE_PLACEHOLDER');
JText::script('COM_JWPAGEFACTORY_MY_ADDONS_NO_ADDON_FOUND');
JText::script('COM_JWPAGEFACTORY_TIP_NO_LICENSE');
JText::script('COM_JWPAGEFACTORY_LIVE_DEMO');
JText::script('COM_JWPAGEFACTORY_ACCESS');

//Add by adan20200222
JText::script('COM_JWPAGEFACTORY_TAB_SHADOW_HORIZONTAL');
JText::script('COM_JWPAGEFACTORY_TAB_SHADOW_VERTICAL');
JText::script('COM_JWPAGEFACTORY_TAB_SHADOW_BLUR');
JText::script('COM_JWPAGEFACTORY_TAB_SHADOW_SPREAD');

//;
JText::script('JGLOBAL_NO_MATCHING_RESULTS');
